[FE] Implement cookie and file upload
georgedobrev/AI_Onboarding pull request #19
Opened 2023-06-08 12:33 UTC by borislavpanov-blankfactor

2023-06-09 07:09 UTC, pyankov00 approved these changes

2023-06-13 10:24 UTC, betinabp commented on src/FrontEnd/src/components/Messages/Messages.tsx
> +                baseUrl="https://localhost:7243/api/"
Instead of passing the baseUrl and uploadEndpoint, create a apiService.ts file and call the fetchWrapper there. Not in the FIleUploader component. The flow of the request should be like this: component calls -> service calls -> fetchWrapper. Components should be passing URL. This `${baseUrl}${uploadEndpoint}` should be done in the service

2023-06-13 10:40 UTC, betinabp requested changes

2023-06-13 10:40 UTC, betinabp commented on src/FrontEnd/src/services/FetchWrapper.tsx
> +): Promise<{ data: T; accessToken?: string; refreshToken?: string }> {
Why do you pass the token here? The token should be sent as a Auth header.

2023-06-13 10:59 UTC, betinabp commented on src/FrontEnd/src/services/authService.ts
> +      const postData = JSON.stringify(formData, null, 2);
Are you sure you need this row?

2023-06-13 14:03 UTC, betinabp approved these changes

2023-06-13 14:03 UTC, merged